### ISSUE TITLE
Why waive the ability to have government customers?

### ISSUE THREAD

**Issue by lupine-dev** [licensezero/prosperity-public-license#5]
Sorry if Issues isn't the place to ask this question, but one part of the license stuck out to me:

> Use by any charitable organization, educational institution, public research organization, public safety or health organization, environmental protection organization, **or government institution** doesn't count as use for a commercial purpose regardless of the source of funding or obligations resulting from the funding.

It looks like this phrase explicitly precludes selling software to a government customer.

I don't think I would be alone in my opinion that in general, government institutions are in a fundamentally different category than the other types of organizations on this list (universities too, maybe, but definitely the others). Charging government customers is not uncommon in the software industry, and is a generally accepted way to earn revenue. Charging charities, public safety and health organizations, and environmental protection organizations is a different thing altogether, in my opinion.

I would be curious to learn more about the reasoning behind this. It might just come down to political belief, but I think it could be productive to discuss.

**Comment by kemitchell** [comment]
@MaxLaumeister this is the perfect place for this question.

The section of Prosperity that you mention comes from [PolyForm-Noncommercial](https://polyformproject.org/licenses/noncommercial/1.0.0/). I was one of the folks involved in writing PolyForm-Noncommercial, too.

The overall purpose of the section from PolyForm-Noncommercial was to address an issue we've seen with Creative Commons NonCommercial terms in the past. Overall, many large organizations, even large organizations that are generally noncommercial in nature, couldn't approve all work under those terms by policy, out of concern that _specific_ uses might arguably count as commercial. The result was often that folks working at university or other organizations that would use the work noncommercially 99+% of the time miss out, because the organization can't approve for 100% and won't spend the legal resources to approve use case by case.

I don't remember hearing a concern about including government institutions when drafting PolyForm-Noncommercial. I definitely remember hearing concerns about including universities. We begrudgingly included the latter in the "safe harbor", despite widespread knowledge that universities frequently conduct research more or less on behalf of for-profit actors and grantmakers.

**Comment by lupine-dev** [comment]
@kemitchell Thank you for sharing this info, the reasoning behind it makes sense. Interesting that no one else voiced that they wanted to reserve the right to sell to government institutions.

In any case, I ended up deciding to use the license as a template for my own custom license. Thank you so much for this resource! For some reason there is a huge lack of cookie-cutter proprietary software licenses out there.

**Comment by kemitchell** [comment]
@MaxLaumeister, take a look at [PolyForm](https://polyformproject.org). It's not just a noncommercial license. There is a whole menu of other options.

**Comment by notpushkin** [comment]
> Interesting that no one else voiced that they wanted to reserve the right to sell to government institutions.

I've actually just noticed that clause as well and came here to raise exactly the same issue. Giving governmental agencies around the world (including Russian Federation or Taliban, for example) permission to use your product for free is not really what you'd want when you apply this license IMO :-)

**Comment by kemitchell** [comment]
As a practical matter, enforcing a copyright license against a foreign government would probably mean bringing a legal claim in that government's own court system. From there, both specific copyright-law rules and more general rules, like sovereign immunity, might prevent an effective copyright claim. But as a practical matter, many firms selling software into government do business primarily with government contractors, rather than with governments directly.

Prosperity is a "noncommercial license". There are plenty of businesses out there selling goods and services primarily to noncommercial users---individuals for personal use, charities, churches, governments, relief organizations. That is their business. But Prosperity (or PolyForm Commercial) are not terms for implementing that approach.
